name: Add Location from Issue
on:
  issues:
    types: [opened]

jobs:
  add-location:
    runs-on: ubuntu-latest
    if: github.event.issue.title == 'Ny Plats'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Parse issue body and update JSON
        id: parse
        run: |
          BODY=$(jq -r .issue.body "$GITHUB_EVENT_PATH")

          NAME=$(echo "$BODY" | grep -A1 '**Namn:**' | tail -n1 | xargs)
          DESC=$(echo "$BODY" | grep -A1 '**Beskrivning:**' | tail -n1 | xargs)
          LAT=$(echo "$BODY" | grep -A1 '**Latitude (lat):**' | tail -n1 | xargs)
          LNG=$(echo "$BODY" | grep -A1 '**Longitude (lng):**' | tail -n1 | xargs)
          ICON=$(echo "$BODY" | grep -A1 '**Ikon:**' | tail -n1 | xargs)
          SCORE=$(echo "$BODY" | grep -A1 '**Poäng:**' | tail -n1 | xargs)

          echo "Parsed values:"
          echo "Name: $NAME"
          echo "Desc: $DESC"
          echo "Lat: $LAT"
          echo "Lng: $LNG"
          echo "Icon: $ICON"
          echo "Score: $SCORE"

          if [[ -z "$NAME" || -z "$LAT" || -z "$LNG" ]]; then
            echo "Missing required fields"
            exit 1
          fi

          # Find the highest existing ID
          MAX_ID=$(jq 'map(.id) | max' locations.json)
          NEW_ID=$((MAX_ID + 1))

          # Create new entry
          NEW_ENTRY=$(jq -n \
            --argjson id "$NEW_ID" \
            --arg lat "$LAT" \
            --arg lng "$LNG" \
            --arg name "$NAME" \
            --arg popupcontent "$DESC" \
            --arg icon "$ICON" \
            --arg score "$SCORE" \
            '{
              id: $id,
              lat: ($lat | tonumber),
              lng: ($lng | tonumber),
              name: $name,
              popupcontent: $popupcontent,
              icon: ($icon | length > 0 ? $icon : null),
              score: ($score | test("^[0-9]+$")? | if . then ($score | tonumber) else null end)
            }')

          echo "New entry: $NEW_ENTRY"

          # Append new entry to JSON array
          jq ". + [ $NEW_ENTRY ]" locations.json > tmp.json && mv tmp.json locations.json

          git add locations.json
          git commit -m "Lade till ny plats från issue #${{ github.event.issue.number }}"
          git push
