name: Add Location from Issue

on:
  issues:
    types: [opened]

permissions:
  contents: write
  issues: read

jobs:
  add_location:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Parse issue body
      id: parse
      run: |
        BODY=$(jq -r .issue.body "$GITHUB_EVENT_PATH")

        get_field() {
          echo "$BODY" | grep -oP "$1:\s*\K.*" | head -n 1
        }

        NAME="$(get_field "Namn")"
        DESC="$(get_field "Beskrivning")"
        LAT="$(get_field "Latitude \(lat\)")"
        LNG="$(get_field "Longitude \(lng\)")"
        ICON="$(get_field "Ikon")"
        SCORE="$(get_field "Poäng")"

        # Fallback null for optional fields
        [ -z "$ICON" ] && ICON=null || ICON="\"$ICON\""
        [ -z "$SCORE" ] && SCORE=null

        echo "Parsed values:"
        echo "Name: $NAME"
        echo "Desc: $DESC"
        echo "Lat: $LAT"
        echo "Lng: $LNG"
        echo "Icon: $ICON"
        echo "Score: $SCORE"

        # Create the new JSON object
        NEW_ITEM=$(jq -n \
          --arg id "$(date +%s)" \
          --arg name "$NAME" \
          --arg desc "$DESC" \
          --arg lat "$LAT" \
          --arg lng "$LNG" \
          --argjson icon "$ICON" \
          --argjson score "$SCORE" \
          '{
            id: ($id | tonumber),
            lat: ($lat | tonumber),
            lng: ($lng | tonumber),
            name: $name,
            popupcontent: $desc,
            icon: $icon,
            score: $score
          }')

        echo "$NEW_ITEM" > new_item.json
        echo "NEW_ITEM=$NEW_ITEM" >> $GITHUB_OUTPUT

    - name: Append to JSON
      run: |
        jq ". + [$(cat new_item.json)]" locations.json > tmp.json && mv tmp.json locations.json

    - name: Commit and push
      run: |
        git add locations.json
        git commit -m "Lade till nya plats från issue #${{ github.event.issue.number }}"
        git push
