name: Add Location from Issue

on:
  issues:
    types: [opened, edited]

jobs:
  add-location:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Parse issue body and add location
      shell: bash
      run: |
        BODY=$(jq -r .issue.body "$GITHUB_EVENT_PATH")

        get_field() {
          echo "$BODY" | grep -A1 "^$1$" | tail -n1 | tr -d '\r'
        }

        NAME="$(get_field "Namn")"
        DESC="$(get_field "Beskrivning")"
        LAT="$(get_field "Latitude (lat)")"
        LNG="$(get_field "Longitude (lng)")"
        ICON="$(get_field "Ikon")"
        SCORE="$(get_field "Poäng")"

        # Convert empty to null, and properly escape values for JSON
        [ -z "$ICON" ] && ICON="null" || ICON=$(jq -R <<< "$ICON")
        [ -z "$SCORE" ] && SCORE="null" || SCORE=$(jq -R <<< "$SCORE")

        echo "Parsed values:"
        echo "Name: $NAME"
        echo "Desc: $DESC"
        echo "Lat: $LAT"
        echo "Lng: $LNG"
        echo "Icon: $ICON"
        echo "Score: $SCORE"

        # Create new JSON object for the location
        NEW_ITEM=$(jq -n \
          --arg id "$(date +%s)" \
          --arg name "$NAME" \
          --arg desc "$DESC" \
          --arg lat "$LAT" \
          --arg lng "$LNG" \
          --argjson icon "$ICON" \
          --argjson score "$SCORE" \
          '{
            id: ($id | tonumber),
            lat: ($lat | tonumber),
            lng: ($lng | tonumber),
            name: $name,
            popupcontent: $desc,
            icon: $icon,
            score: $score
          }')

        echo "New item JSON:"
        echo "$NEW_ITEM"

        # Add the new item to locations.json
        jq ". + [ $NEW_ITEM ]" locations.json > locations_tmp.json
        mv locations_tmp.json locations.json

        # Commit and push changes
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        git add locations.json
        git commit -m "Lade till ny plats: $NAME"
        git push
